### ISSUE TITLE
참가 신청서는 팀원 모두가 써야하나요?

### ISSUE THREAD

**Issue by samslow** [Naver-AI-Hackathon/AI-Vision#1]
참가 동의서를 팀원 각각 제출하려했는데 1개밖에 올라가지않아 중복된 내용으로 하나 더 써야하는지 문의드립니다.

**Comment by Hackoperation** [comment]
안녕하세요. 
이미 제출하셨더라도, 신청폼 수정이 가능합니다. 참가하실 팀원 정보를 모두 기입하여 수정 제출해주시면 됩니다~

고맙습니다.

**Comment by samslow** [comment]
제가 원하는 답변이 아닙니다..!
신청폼에 팀원 정보를 모두 기입했는데 맨위에 참가동의서파일은 1개밖에 올라가지않습니다. 
2명이면 2개를 올릴수있어야하는데 이에대한 답변 부탁드립니다.

**Comment by Hackoperation** [comment]
@samslow 
참가동의서에는 팀명/(모든)참가 팀원 이름/팀원 생년 월일을 각 기입하여 다시 업로드부탁드립니다.

**Comment by samslow** [comment]
네 그럼 참가 동의서에 임의로 칸을 만들어 서명을 넣는 방향으로 하겠습니다.
폼은 수정 가능합니다만 파일은 수정이 안되는 것 같습니다. 새로 써야할까요 ?
