### ISSUE TITLE
ConnectionResetError: [Errno 104] 

### ISSUE THREAD

**Issue by MinMolang** [Naver-AI-Hackathon/AI-Vision#111]
안녕하세요
model을 save 하는 과정중에 

**log 

model saved!Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request six.raise_from(e, None) File "<string>", line 2, in raise_from File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request httplib_response = conn.getresponse() File "/opt/conda/lib/python3.5/http/client.py", line 1198, in getresponse response.begin() File "/opt/conda/lib/python3.5/http/client.py", line 297, in begin
response.begin() File "/opt/conda/lib/python3.5/http/client.py", line 297, in begin version, status, reason = self._read_status() File "/opt/conda/lib/python3.5/http/client.py", line 258, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/opt/conda/lib/python3.5/socket.py", line 576, in readinto return self._sock.recv_into(b)ConnectionResetError: [Errno 104] Connection reset by peerDuring handling of the above exception, another exception occurred:Traceback (most recent call last): File "main.py", line 269, in <module> nsml.save(checkpoint=check) File "/app/nsml/client.py", line 359, in save os.path.join(file_name, base_filename) File "/opt/conda/lib/python3.5/site-packages/minio/api.py", line 534, in fput_object content_type, metadata) File "/opt/conda/lib/python3.5/site-packages/minio/api.py", line 740, in put_object data, length, metadata=metadata)
File "/opt/conda/lib/python3.5/site-packages/minio/api.py", line 1461, in _stream_put_object metadata) File "/opt/conda/lib/python3.5/site-packages/minio/api.py", line 1571, in _new_multipart_upload headers=metadata) File "/opt/conda/lib/python3.5/site-packages/minio/api.py", line 1736, in _url_open
preload_content=preload_content) File "/opt/conda/lib/python3.5/site-packages/urllib3/poolmanager.py", line 322, in urlopen response = conn.urlopen(method, u.request_uri, **kw) File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen _stacktrace=sys.exc_info()[2]) File "/opt/conda/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment raise six.reraise(type(error), error, _stacktrace) File "/opt/conda/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise raise value.with_traceback(tb) File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request six.raise_from(e, None) File "<string>", line 2, in raise_from File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request httplib_response = conn.getresponse() File "/opt/conda/lib/python3.5/http/client.py", line 1198, in getresponse response.begin() File "/opt/conda/lib/python3.5/http/client.py", line 297, in begin version, status, reason = self._read_status() File "/opt/conda/lib/python3.5/http/client.py", line 258, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/opt/conda/lib/python3.5/socket.py", line 576, in readinto return self._sock.recv_into(b)urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))User session exited
다음과 같은 error가 뜨고 
save되었다고 떴던 model 1 을 찾을 수 없다고 뜨는 데 어떤 문제인지 궁금합니다ㅜㅜ!!감사합니다``

**Comment by MinMolang** [comment]
team_33/ir_ph1_v2/89
team_33/ir_ph1_v2/94 입니다 감사합니다!!

**Comment by MinMolang** [comment]
같은 코드를 가지고 다른 팀원은 잘 돌아가지만 제가 진행했을 때만 문제가 생기는 것 같습니다!

**Comment by heasungkim** [comment]
@MinMolang  
@nsml-admin 
@Hackoperation 

같은 문제를 겪고 있습니다. 어떻게 해결하셨나요???

**Comment by MinMolang** [comment]
> @MinMolang
> @nsml-admin
> @Hackoperation
> 
> 같은 문제를 겪고 있습니다. 어떻게 해결하셨나요???

일시적으로 일어났던 문제 같아서 이후 지속적으로 다시 시도했더니 학습이 가능하였습니다!

**Comment by ttagu99** [comment]
저도 같은문제가 있습니다. 해결하신분 계신가요?
sesstion name은 "Zonber/ir_ph1_v2/275" 입니다..

**Comment by ttagu99** [comment]
저는 해결했습니다. 정확한 원인 파악은 못했지만.. bind 함수를 한 session에서 여러번 쓰던것을 한번으로 줄이니 같은에러 발생하지 않네요. 다른분들도 참고하세요~~

**Comment by heasungkim** [comment]
@ttagu99 

bind 함수를 한 세션에서 여러번 쓰셨다는것이 어떤 의미인지 잘 이해가 가지 않습니다.
원래 bind_model 은 한번만 쓰고 nsml.load, nsml.save 등을 이용하지 않나요?

어떻게 해결하신건지 구체적으로 설명해주시면 감사하겠습니다.

**Comment by ttagu99** [comment]
> @ttagu99
> 
> bind 함수를 한 세션에서 여러번 쓰셨다는것이 어떤 의미인지 잘 이해가 가지 않습니다.
> 원래 bind_model 은 한번만 쓰고 nsml.load, nsml.save 등을 이용하지 않나요?
> 
> 어떻게 해결하신건지 구체적으로 설명해주시면 감사하겠습니다.

 제 pipeline과 @heasungkim  님의 pipeline이 다를 거라서 정확한 답을 드릴 수 없을거 같지만, 제 경우에 대한 현상을 설명 드리면 아래와 같습니다. 해결책 찾으시는데 실마리가 될수 있기를 바랍니다.
![image](https://user-images.githubusercontent.com/10820453/51086520-29c24000-178b-11e9-942b-03e31e0655d3.png)
![image](https://user-images.githubusercontent.com/10820453/51086523-38105c00-178b-11e9-912b-6763f3eb741d.png)

**Comment by HyunjiEllenPak** [comment]
> > @ttagu99
> > bind 함수를 한 세션에서 여러번 쓰셨다는것이 어떤 의미인지 잘 이해가 가지 않습니다.
> > 원래 bind_model 은 한번만 쓰고 nsml.load, nsml.save 등을 이용하지 않나요?
> > 어떻게 해결하신건지 구체적으로 설명해주시면 감사하겠습니다.
> 
> 제 pipeline과 @heasungkim 님의 pipeline이 다를 거라서 정확한 답을 드릴 수 없을거 같지만, 제 경우에 대한 현상을 설명 드리면 아래와 같습니다. 해결책 찾으시는데 실마리가 될수 있기를 바랍니다.
> ![image](https://user-images.githubusercontent.com/10820453/51086520-29c24000-178b-11e9-942b-03e31e0655d3.png)
> ![image](https://user-images.githubusercontent.com/10820453/51086523-38105c00-178b-11e9-912b-6763f3eb741d.png)

@ttagu99 안녕하세요~! 혹시 위에 첨부해주신 그림과 같이 코드 한번 실행하여 bind_model한번 호출하여 여러개의 모델을 로드하는 것을 어떻게 구현하였는지 조그만 자세하게 말씀해주실 수 있을까요? 저희도 infer에서 여러개의 모델을 로드하여 submit을 하려고 하는데, 
예를 들어서 모델A,B,C가 있을때, submit시에 bind_model에 하나의 모델정보만 넘겨줄 수 있어서 모델A를 로드하면 infer함수가 자동으로 실행이 되고, 제출이 됩니다. 모델 A를 로드하고 이어서 모델B와 C를 로드하려면 어떻게 해야 하는 건지요?@@

**Comment by ttagu99** [comment]
> > > @ttagu99
> > > bind 함수를 한 세션에서 여러번 쓰셨다는것이 어떤 의미인지 잘 이해가 가지 않습니다.
> > > 원래 bind_model 은 한번만 쓰고 nsml.load, nsml.save 등을 이용하지 않나요?
> > > 어떻게 해결하신건지 구체적으로 설명해주시면 감사하겠습니다.
> > 
> > 
> > 제 pipeline과 @heasungkim 님의 pipeline이 다를 거라서 정확한 답을 드릴 수 없을거 같지만, 제 경우에 대한 현상을 설명 드리면 아래와 같습니다. 해결책 찾으시는데 실마리가 될수 있기를 바랍니다.
> > ![image](https://user-images.githubusercontent.com/10820453/51086520-29c24000-178b-11e9-942b-03e31e0655d3.png)
> > ![image](https://user-images.githubusercontent.com/10820453/51086523-38105c00-178b-11e9-912b-6763f3eb741d.png)
> 
> @ttagu99 안녕하세요~! 혹시 위에 첨부해주신 그림과 같이 bind_model한번 호출하여 여러개의 모델을 로드하는 것을 어떻게 구현하였는지 조금만 자세하게 말씀해주실 수 있을까요?
> 
> 저희도 infer에서 여러개의 모델을 로드하여 submit을 하려고 하는데 어려움이 있어서 질문드립니다~ㅠ
> bind_model에 하나의 모델정보만 넘겨줄 수 있는 것 같은데, 이런상황에서 모델A,B,C를 모두 로드하고 싶을 때, submit을 하면 모델A를 로드 한후 infer함수가 자동으로 실행이 되어 제출이 되버립니다. 모델 A를 로드하고 이어서 모델B와 C를 로드하려면 어떻게 해야 하는 건지요?ㅠ

 저도 infer에서 여러개의 모델을 로드해서 사용해보지는 않았습니다만... 비슷한 모델 구조를 가지고 있다면 한개의 모델로 merge해서 저장후 bind하고, infer에서 해당 모델을 로딩한후 쪼개서 사용할 수도 있을꺼 같습니다.

**Comment by MinMolang** [comment]
Closed Issue
