### ISSUE TITLE
Github 계정으로 sign in 하려고 하는데 다음과 같은 메세지만 뜹니다.

### ISSUE THREAD

**Issue by ChangmoKang** [Naver-AI-Hackathon/AI-Vision#15]
You are not a registered user. Please contact the administrator. ( dl_nsml_alpha@navercorp.com )

어떻게 해야하나요?

**Comment by nsml-admin** [comment]
아직 접수기간이라서 사용자 등록이 안된상태입니다.

**Comment by ChangmoKang** [comment]
답변 감사드립니다. 한 가지 더 여쭙겠습니다. 그럼 예선 100팀에 들어가 그때부터 튜토리얼을 해볼 수 있는건가요?
