### ISSUE TITLE
대회와 관련이 없지만 지난 대회의 데이터에 대해 궁금한 것이 있습니다.

### ISSUE THREAD

**Issue by HeoTaksung** [Naver-AI-Hackathon/AI-Vision#40]
어디에 여쭤봐야 할지 잘 몰라서 여기에 글을 남깁니다.

3~4월에 열린 2018년 네이버 AI 해커톤에서 문장 유사도 측정하는 데이터를 얻고자 하는데
이 데이터가 비공개로 되어 얻을 수 없는 것인지 궁금합니다.

혹시 데이터를 얻을 수 있다면 어디서 얻을 수 있는지 궁금합니다.

**Comment by Hackoperation** [comment]
해당데이터는 저작권 문제등으로 공유가 금지 되어있습니다.

도움을드리지못해서 죄송합니다.
