### ISSUE TITLE
팀 이름을 정해서 냈는데 NSML 상에서는 팀 이름이 team_XX로 뜹니다.

### ISSUE THREAD

**Issue by samslow** [Naver-AI-Hackathon/AI-Vision#49]
제출한 폼에서 사용한 팀 이름으로 나오지 않고 팀이름이 임의로 붙여 진 것 같은데 확인 부탁드립니다!

**Comment by Hackoperation** [comment]
안녕하세요. 

임시 팀명이 나타나는 것은 처음에 신청해주신 팀명이 등록 조건에 부합하지 않아서 인데요.
해당 팀(대표자)분들께는 수정 등록하시도록 안내 메일 드렸으니 참고 부탁드리겠습니다~

고맙습니다.

**Comment by samslow** [comment]
안내메일에 나온대로 영어로만 이루어진 팀명인데.. 어떻게 바꿔야할까요?

**Comment by samslow** [comment]
> 안녕하세요.
> 
> 임시 팀명이 나타나는 것은 처음에 신청해주신 팀명이 등록 조건에 부합하지 않아서 인데요.
> 해당 팀(대표자)분들께는 수정 등록하시도록 안내 메일 드렸으니 참고 부탁드리겠습니다~
> 
> 고맙습니다.

안내메일에 나온대로 영어로만 이루어진 팀명인데.. 어떻게 바꿔야할까요?

**Comment by nsml-admin** [comment]
@samslow 
최초 제출한 팀으로 모두 변경하였습니다. 
다만, leaderboard에서만 변경되어 보입니다.
