### ISSUE TITLE
관련 분야 지식

### ISSUE THREAD

**Issue by devGW** [Naver-AI-Hackathon/AI-Vision#9]
관련분야지식이 많이 부족해도
따라가는데 문제가 없을까요?

**Comment by Hackoperation** [comment]
딥러닝 기반 지식은 필요하며, image retrieval이 아닌 다른 computer vision task에 경험이 있으시다면 image retrieval 문제는 빠르게 이해할 수 있을 것 같습니다. 혹시 computer vision task에 경험이 부족하시다면 공개되어 있는 toy example들을 가지고 연습해보시는 것을 추천합니다 :)
